server:
  port: 7001

eureka:
  instance:
    hostname: eureka01.com
  client:
    #自己就是注册中心，职责是维护服务实例，不需要去检索服务
    fetch-registry: false
    #不向注册中心注册自己
    register-with-eureka: false
    service-url:
      #设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka02.com:7002/eureka/
  server:
    #关闭自我保护机制，保证不可用的服务被及时剔除
    enable-self-preservation: false