server:
  port: 80
  servlet:
    context-path: /consumer

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka01.com:7001/eureka,http://eureka02.com:7002/eureka

ribbon:
  ReadTimeout: 2000
  connectTimeout: 2000
#日志查看
logging:
  level:
    com.youxu.springcloud.service.PaymentFeignService: debug

