server:
  port: 80
  servlet:
    context-path: /consumer

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka01.com:7001/eureka,http://eureka02.com:7002/eureka

ribbon:
  #相当于socketTimeout，数据交互处理的时间
  ReadTimeout: 4000
  #建立连接的时间
  connectTimeout: 1000
#开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true
